name: finalproject
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_swiper_null_safety: ^1.0.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dog.png
    - assets/test.jpg
    - assets/cat.png
    - assets/bird.png
    - assets/rabbit.png
    - assets/horse.png
    - assets/ferret.png
    - assets/fish.png
    - assets/snake.png
    - assets/other.png
    - assets/grooming.png
    - assets/consultation.png
    - assets/vaccination.png
    - assets/logo.png
    - assets/details.png
    - assets/calendar.png
    - assets/login2bg.png
    - assets/registerbg.png
    - assets/clinic.jpg

  fonts:
    - family: Josefin-Sans
      fonts:
        - asset: assets/JosefinSans-VariableFont_wght.ttf